name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install project dependencies
        run: npm install

      - name: Install htmlhint globally
        run: npm install -g htmlhint

      - name: Run HTMLHint to check HTML files
        run: htmlhint "**/*.html"

      - name: Run Stylelint to check CSS files
        run: npx stylelint "**/*.css"
